feature : CountryNameMapper
cs-kmitl-2017/group1 pull request #21
Opened 2017-12-08 15:53 UTC by nukkung999

2017-12-08 17:17 UTC, champillon requested changes
ฝากชี้แจงด้วยครับ

2017-12-08 17:17 UTC, champillon commented on src/main/java/th/ac/kmitl/science/comsci/example/models/CountryName.java
> +            default : return 0;
ทำไม default return 0 หล่ะ ไม่ throw Exception

2017-12-09 16:02 UTC, champillon approved these changes
LGTM la

2017-12-09 16:02 UTC, thebankky approved these changes
LGTM krub

2017-12-09 16:06 UTC, merged