Features : Create Address and Test class
cs-kmitl-2017/group1 pull request #8
Opened 2017-12-03 05:51 UTC by nukkung999

class will contains about address content

2017-12-03 07:09 UTC, champillon requested changes
แก้ไขด้วยนะครับ

2017-12-03 07:09 UTC, champillon commented on src/main/java/th/ac/kmitl/science/comsci/example/models/Address.java
> +
เว้นไว้ทำไมครับ???

2017-12-03 07:09 UTC, champillon commented on src/main/java/th/ac/kmitl/science/comsci/example/models/Address.java
> +    private int citySubDivisionSection;
field นี้ไว้ทำอะไรครับ

2017-12-03 07:09 UTC, champillon commented on src/main/java/th/ac/kmitl/science/comsci/example/models/Address.java
> +    private String Village;
ชื่อตัวแปรขึ้นต้นด้วยตัวเล็กครับ

2017-12-03 07:09 UTC, champillon commented on src/main/java/th/ac/kmitl/science/comsci/example/models/Address.java
> +    public void setAddress(String houseAddress,
ใช้เป็น constructor ดีกว่ามั้ยครับ

2017-12-03 07:09 UTC, champillon commented on src/main/java/th/ac/kmitl/science/comsci/example/models/Address.java
> +    public String[] getAddress(){
ทำไมคืนเป็น String array ครับ

2017-12-03 07:09 UTC, champillon commented on src/test/java/th/ac/kmitl/science/comsci/example/models/AddressTest.java
> +public class AddressTest {
Test ไม่ครบทุกฟิลด์ครับ

2017-12-03 07:32 UTC, nukkung999 commented on src/main/java/th/ac/kmitl/science/comsci/example/models/Address.java
> +    private int citySubDivisionSection;
houseAddress เก็บบ้านเลขที่ครับ <---
village เก็บหมู่บ้านครับ ในใบมันมี
citySubDivisionSection เก็บ หมู่ที่ครับ <---
<---ไม่รู้จะใช้คำไหนจริงๆ

2017-12-03 07:38 UTC, nukkung999 commented on src/main/java/th/ac/kmitl/science/comsci/example/models/Address.java
> +    public String[] getAddress(){
คือไว้สำหรับคนที่ต้องการค่าใน instance ทุก field พร้อมกันเลยครับ จะได้ไม่ต้องมาเรียก get ทีละตัว แล้วข้อมูลส่วนใหญ่เป็น String ผมเลย Casting เลขหมู่ ให้เป็นString ด้วย

2017-12-03 13:58 UTC, champillon requested changes
แก้ตาม comments ด้วยครับ สู้ๆนะครับ ^^b

2017-12-03 13:58 UTC, champillon commented on src/main/java/th/ac/kmitl/science/comsci/example/models/Address.java
> +    public String[] getAddress(){
พี่ว่ายังไม่มีใครใช้ ยังไม่ควรสร้าง method นี้ดีมั้ยครับ
ถ้ามีคนใช้ ค่อยสร้าง เพราะพี่กลัวว่ามันจะ over-engineering แล้วไม่ได้ใช้

2017-12-03 13:58 UTC, champillon commented on src/test/java/th/ac/kmitl/science/comsci/example/models/AddressTest.java
> +        assert (resultArray[0].contains("1103/52"));
ถ้าจะ test อะไรหลายๆอย่าง พี่ว่าแยกเป็น test case ย่อยดีมั้ยครับ
1 test ทดสอบ 1 อย่าง จะได้แยก test เป็นอิสระต่อกัน
เผื่ออนาคต test ในบางอย่างจะเปลี่ยน จะได้แยกกันแก้

2017-12-03 13:58 UTC, champillon commented on src/main/java/th/ac/kmitl/science/comsci/example/models/Address.java
> +        houseAddress = "";
houseAddress คืออะไรครับ มันงงว่า class ชื่อ Address แล้วกลับมีตัวแปรซ้ำซื้อชื่อ houseAddress ครับ

2017-12-04 11:57 UTC, thebankky requested changes

2017-12-04 11:57 UTC, Thel3ankky commented on src/main/java/th/ac/kmitl/science/comsci/example/models/Address.java
> +                   int citySubDivisionSection,
ทำไม citySubDivisionSection ถึงเป็น int แล้วไป .toString ทีหลังหล่ะครับ
ทำไมถึงไม่เป็น String ตั้งแต่แรก

2017-12-04 11:57 UTC, Thel3ankky commented on src/main/java/th/ac/kmitl/science/comsci/example/models/Address.java
> +    public Address(){
จำเป็นต้องมี constructor เปล่าแบบนี้ด้วยหรอครับ

2017-12-04 11:57 UTC, Thel3ankky commented on src/main/java/th/ac/kmitl/science/comsci/example/models/Address.java
> +    public Address(String houseAddress,
ไม่เห็นมีการเรียกใช้ Constructor ตัวนี้เลยนะครับ

2017-12-04 11:57 UTC, Thel3ankky commented on src/test/java/th/ac/kmitl/science/comsci/example/models/AddressTest.java
> +    @Test
มีวิธี test ที่ดีกว่านี้ไหมครับ แบบนี้ก็ดีนะ
แต่พี่ว่ามันดูยืดเยื้อเกินไปรึเปล่าครับ

2017-12-04 12:39 UTC, nukkung999 commented on src/main/java/th/ac/kmitl/science/comsci/example/models/Address.java
> +                   int citySubDivisionSection,
ไว้ป้องกันการเก็บค่าพลาดครับ เพราะ หมู่ที่ในประเทศไทยผมยังไม่เห็นมีแบบตัวอักษร แต่ที่จะ Return เป็น String คือ ต้องการให้ไปเป็น Array ซึ่งจะคืนค่าได้ง่ายกว่า(ในความคิดผม)ครับ

2017-12-04 12:40 UTC, nukkung999 commented on src/main/java/th/ac/kmitl/science/comsci/example/models/Address.java
> +    public Address(String houseAddress,
ผมสร้างรองรับกับคลาสต่อไปที่จะเรียกไปทำงานครับ

2017-12-04 12:42 UTC, nukkung999 commented on src/main/java/th/ac/kmitl/science/comsci/example/models/Address.java
> +    public Address(){
Zero Argrument ผมทำไว้เพื่อเวลาสร้างคลาสตอนเทสผมไม่ต้องอัด Argrument เข้ามาตอนสร้าง Instance ทั้งหมดครับ เพราะตอนเทสผมมีการเทสเฉพาะ Attribute ด้วยครับ จะได้อัดเข้ามาแค่บาง Attribute ด้วยครับ

2017-12-04 12:42 UTC, nukkung999 commented on src/test/java/th/ac/kmitl/science/comsci/example/models/AddressTest.java
> +    @Test
ผมคิดวิธีที่จะเทสทั้ง Object ไม่ออกจริงๆครับ

2017-12-04 14:35 UTC, champillon commented on src/test/java/th/ac/kmitl/science/comsci/example/models/AddressTest.java
> +    @Test
Address address = new Address(houseAddress, ...);

assertEquals(address.getHouseAddress, houseAddress);

อย่างงี้ก็ได้ครับ

2017-12-04 14:39 UTC, champillon commented
@nukkung999 เราว่า code นายอ่ะ "แทบ" ไม่ได้คิดถึงการใช้งานเลยนะ
พอนายไม่รู้ว่านายจะใช้งานของพวกนี้ยังไง
ทำให้นายออกแบบ "เผื่อ" อะไรหลายๆอย่าง
ซึ่งอะไรหลายๆอย่างนั้นก็ไม่รู้ว่าจะได้ใช้จริง
หรือไม่ได้ใช้จริงในอนาคต แต่มันก็มีเผื่อไว้

พอเราเผื่อของที่ไม่ได้ใช้ไว้เยอะ เราก็จะไม่กล้าลบมันออกจาก code
เพราะเราไม่เข้าใจที่มาของมันว่ามันมาจากตรงไหน เอาไว้ทำอะไร
สุดท้าย code นายก็จะบวมขึ้นเรื่อยๆ เพราะเต็มไปด้วยของที่ "เผื่อ" ไว้
จนสุดท้ายบวมมากๆ ก็แยกออกจากกันเป็น component ย่อยๆไม่ได้

อันนี้ที่พี่ๆเค้าถามคืออยากให้ปรับแก้ของที่เผื่อไว้
เพราะถ้ามี "เคสที่จะต้องใช้จริง" ซึ่งไม่ใช่เคสที่ "เผื่อ" อะไรไว้
ของพวกนั้นก็ควรอยู่ใน code ครับ
อะไรที่ไม่ได้ใช้ ก็ไม่ต้อง "เผื่อ" ไว้ใน code ครับ

2017-12-04 14:39 UTC, champillon commented on src/main/java/th/ac/kmitl/science/comsci/example/models/Address.java
> +                   int citySubDivisionSection,
มันไม่มีเคสการใช้งานจริง ไม่อยากให้เดาและ "เผื่อ" ไว้ครับ ไม่งั้นอนาคตมันจะเผื่อไปเรื่อยๆครับ

2017-12-04 14:41 UTC, champillon commented on src/main/java/th/ac/kmitl/science/comsci/example/models/Address.java
> +    public Address(){
คือการมี หรือไม่มี zero argument นี่คือ อยู่ที่ว่า ค่าในนั้นต้องถูก set ตอนสร้าง object เลย หรือว่า set หลังจากสร้าง object ไว้แล้วได้ครับ

ดังนั้นถ้าไม่มีเคสการใช้งานแบบนี้ พี่ว่าตัดออกดีกว่าครับ

ที่นายต้องตอบเราว่าจะคงไว้คือ ทำไมจึงอนุญาติให้ object นี้สร้างได้ 2 แบบครับ

2017-12-04 14:41 UTC, champillon commented on src/main/java/th/ac/kmitl/science/comsci/example/models/Address.java
> +    public Address(String houseAddress,
ช่วยระบุคลาสที่จะรองรับพร้อมยกตัวอย่างด้วยครับ

2017-12-04 16:19 UTC, champillon requested changes
เริ่มดีแล้วครับ ฝากแก้อีกนิดหน่อยก็น่าจะ ok แล้วครับ

2017-12-04 16:19 UTC, champillon commented on src/main/java/th/ac/kmitl/science/comsci/example/models/Address.java
> +    private String houseNumber;
เว้น 1 บรรทัดครับ แยก class กับ attribute

2017-12-04 16:19 UTC, champillon commented on src/main/java/th/ac/kmitl/science/comsci/example/models/Address.java
> +    private String village;
กะลังคิดว่า เพื่อนๆ จะเข้าใจตรงกันเรารึป่าว มีกลุ่มอื่นเราเปลี่ยนให้ไปใช้ lineOne, lineTwo, ... ให้ตรงกับใน spec ของ ETDA น่าจะดีกว่า

2017-12-04 16:19 UTC, champillon commented on src/main/java/th/ac/kmitl/science/comsci/example/models/Address.java
> +    public String[] getAddress(){
อันนี้ไม่ตัดออกหรอครับ หรือหาเคสที่จะใช้ตาม spec ของ ETDA ได้

2017-12-05 03:51 UTC, champillon approved these changes
LGTM แล้ว แต่เว้นให้ 1 บรรทัดเหอะ!!! ไม่งั้น -1

2017-12-05 03:51 UTC, champillon commented on src/main/java/th/ac/kmitl/science/comsci/example/models/Address.java
> +    private String line1;
ยังย้ำว่า ตรงนี้ให้เว้น 1 บรรทัดครับ ระหว่างชื่อ class กับ attribute ตัวแรก ถ้ารอบหน้าไม่เว้นมา พี่ "-1" นะครับ

2017-12-05 03:53 UTC, mahasak approved these changes
LGTM

2017-12-05 03:54 UTC, merged

2017-12-05 04:07 UTC, champillon commented
ตัดคะแนนดังนี้

1. design as components (1 คะแนน) => ยังไม่ให้เต็ม 2 คะแนน เพราะยังไม่ได้ใช้ design pattern ที่ยากกว่านี้ ลองหาส่วนอื่นนอกจาก model ทำดูครับ มันมีจุดที่ได้ใช้ design pattern ที่ยากกว่านี้ แล้วจะได้คะแนนเต็ม 2 คะแนนครับ (ถ้าทำได้สมบูรณ์)

2. naming & convention (0.25 คะแนน) => ตัดคะแนนดังนี้
2.1 บางทีชื่อตัวแปรเป็นตัวใหญ่บ้าง และลืมเป็น Camel Case
2.2 การจัด Spacing ของย่อหน้า และบรรทัด ยังไม่เหมาะสม
2.3 การตั้งชื่อตัวแปรไม่สื่อให้เพื่อนๆเขียน code ต่อได้ง่าย เช่น houseAddress ใน class Address มันดูตลกว่าใน Address ดันมี houseAddress อีก ซ้ำซ้อนกันไป

3. technology leveraging (0 คะแนน) => ยังไม่ได้ใช้ tech อะไรยากครับ ไม่มีคะแนนให้

4. git usage (0.75 คะแนน) => ตัด 0.25 คะแนน เพราะ commit log เวลาแก้อะไรไป เช่น remove unused field ช่วยระบุด้วยครับ ว่า field ที่ remove ไปมันมือ field อะไร เพราะเวลาเรา roll back เราจะได้รู้เลยว่า version นี้อะไรหายไป ไม่งั้นต้องเปิดดูไฟล์เทียบกันอีกทีครับ

สู้ๆนะครับ PR ต่อๆไปจะดีขึ้นครับ
@nukkung999