Add ElectronicAddressClass and Use ElectronicAddressClass in CompanyC…
cs-kmitl-2017/group1 pull request #9
Opened 2017-12-03 11:33 UTC by poyapoyassgit

…lass

2017-12-03 14:06 UTC, champillon commented
...lass คืออะไรครับ???

2017-12-03 14:09 UTC, champillon requested changes
ฝากแก้ไขตาม comments ด้วยนะครับ

2017-12-03 14:09 UTC, champillon commented on src/main/java/th/ac/kmitl/science/comsci/example/models/Company.java
> +    private ElectronicAddress ElectronicAddress;
1. ชื่อตัวแปรเป็นตัวเล็กครับ (ส่วนชื่อ class ตัวใหญ่ครับ)
2. ทำไมตั้งชื่อว่า ElectronicAddress ครับ

2017-12-03 14:09 UTC, champillon commented on src/test/java/th/ac/kmitl/science/comsci/example/models/ElectronicAddressInCompanyTest.java
> +	String Email = "Cat";
จัด spacing ด้วยครับ มันเบี้ยวจากบรรทัดบน

2017-12-03 14:09 UTC, champillon commented on src/test/java/th/ac/kmitl/science/comsci/example/models/ElectronicAddressInCompanyTest.java
> +	seller.setElectronicAddress(urlID, Email);
แยก test กันครับ
test ว่า ElectronicAddress นั้นถูก สร้าง instance และ set ค่าได้รึป่าว อันนึง

และ test ว่า Company นั่น set electronicAddress ได้รึป่าวนั้นอีกอันนึงครับ

2017-12-03 14:09 UTC, champillon commented on src/test/java/th/ac/kmitl/science/comsci/example/models/ElectronicAddressTest.java
> +        String Email = "Cat";
mock data test ของ email ให้สมจริงด้วยครับ

2017-12-03 14:19 UTC, poyapoyassgit commented on src/main/java/th/ac/kmitl/science/comsci/example/models/Company.java
> +    private ElectronicAddress ElectronicAddress;
ข้อ 2 เพราะ เป็นภายในคลาส บรรจุ URL กับ E-Mail ผมเลยเรียกว่าเป็นการที่อยู่บนโลก Electronic ครับ

2017-12-03 15:32 UTC, champillon commented
@poyapoyassgit ยังรอคำตอบอยู่นะครับ ว่าทำไมถึงตั้งชื่อว่า ElectronicAddress ครับ

2017-12-03 15:35 UTC, champillon requested changes
แก้ตาม comments ด้วยนะครับ
ถ้าอันไหน comments เกิน 2รอบแล้วไม่แก้ จะขอ "-1" ตามจุดที่ไม่แก้นะครับ

2017-12-03 15:35 UTC, champillon commented on src/main/java/th/ac/kmitl/science/comsci/example/models/Company.java
> +        if(electronicaddress == null) {
ถ้าเขียนแบบนี้ แปลว่า set ค่าได้ครั้งเดียว ควรมี test ด้วยครับว่า set ค่าครั้งแรกได้ และ set ค่าครั้งที่ 2 ไม่เปลี่ยน

แต่คำถามคือ มันควรอยู่เป็น method แบบนี้ หรือเป็นคำว่า initialElectronicAddress ครับ เพราะมัน set ได้ครั้งเดียว

2017-12-03 15:35 UTC, champillon commented on src/test/java/th/ac/kmitl/science/comsci/example/models/ElectronicAddressInCompanyTest.java
> +        seller.setElectronicAddress(urlID, Email);
อันนี้ยังไม่แก้ตามที่ comment ไปให้แยก test นะครับ
แยก test ระหว่าง สร้าง ElectronicAddress กับ set ค่า electronicAddress ให้ Company
ถ้าไม่แก้ตามที่ comment พี่จะเริ่ม "-1" แล้วนะครับ

2017-12-03 15:35 UTC, champillon commented on src/test/java/th/ac/kmitl/science/comsci/example/models/ElectronicAddressInCompanyTest.java
> +    public void shouldInitPropertyViaConstuctorCorrectly(){
ชื่อ method เป็น initial via constructor ทำไมมี code ส่วนที่ไม่ใช่ constructor ด้วยครับ?

2017-12-03 16:30 UTC, champillon commented
@poyapoyassgit  มาถามในนี้เลยครับ

2017-12-03 16:36 UTC, poyapoyassgit reviewed
ผมต้อง สร้าง methodในtest ให้เป็นหลายส่วนถ้าเรามีส่วนที่ต้อง test มากกว่า 1 ส่วนใช่ไหมครับ

2017-12-03 16:36 UTC, poyapoyassgit commented on src/test/java/th/ac/kmitl/science/comsci/example/models/ElectronicAddressInCompanyTest.java
> +        seller.setElectronicAddress(urlID, Email);
ผมควรจะแยก method ว่า test อะไรให้เป็นส่วนๆใช่ไหมครับ

2017-12-03 16:46 UTC, champillon requested changes
ลบ ElectronicAddressInCompanyTest แล้วย้ายไปใช้ CompanyTest แทนนะครับ สำหรับเคสที่ถามมา เพราะมันเป็น behavior ของ CompanyTest ครับ

2017-12-03 16:46 UTC, champillon commented on src/test/java/th/ac/kmitl/science/comsci/example/models/ElectronicAddressInCompanyTest.java
> +        seller.setElectronicAddress(urlID, Email);
โทษทีเราดูผิด จริงๆ นายจะทำ 2 อย่างคือ
1. test ว่า set ElectronicAddress ครั้งที่ 1 แล้วได้ค่า
2. test ว่า set ElectronicAddress ครั้งที่ 2 แล้วก็ได้ค่า
ถูกมะ
ดังนั้น ควรแบ่งเป็น 2 test คือ
1. ชื่อ method canInitialElectronicAddress
2. ชื่อ method cannotChangeElectronicAddress
ถูกรึป่าว
และ 2 method นี้ควรอยู่ใน CompanyTest เพราะมันเป็น behavior ของ Company ถูกมะ?

2017-12-03 16:48 UTC, champillon commented
@poyapoyassgit ปกติเราทำแบบนี้ครับ
มี 1 class ก็จะมี 1 test ประกบ เช่น Company กับ CompanyTest
หรือ ElectronicAddress กับ ElectronicAddressTest

โดยถ้าเกิด association กันระหว่าง Company กับ ElectronicAddress ให้ดูว่าที่เกิดขึ้นเป็น behavior ของใคร แล้วเอาไปใส่ test ของคนนั้นครับ

ในกรณีนี้คือ behavior ของ Company ที่ควรจะ set ให้มี ElectronicAddress ได้ครับ

2017-12-03 17:47 UTC, champillon requested changes
เริ่มดีแล้วครับ แก้และชี้แจงใน comments อีกนิดครับ

สู้ครับ ^^b

2017-12-03 17:47 UTC, champillon commented on src/main/java/th/ac/kmitl/science/comsci/example/models/Company.java
> +        if(universalcommunication == null) {
ตรงนี้ทำไมต้องให้มัน set ได้ครั้งเดียวครับ (อยากรู้เหตุผล)

2017-12-03 17:47 UTC, champillon commented on src/test/java/th/ac/kmitl/science/comsci/example/models/CompanyTest.java
> +    public void canInitialUniversalCommunication(Company seller) {
ใส่ @Test ข้างบนนี้ครับ แล้ว test จะถูก run แล้วไม่ต้องไปเพิ่มใน บรรทัด 21 กับ 22 ครับ (ดูบรรทัด 7 เป็นตัวอย่างก็ได้ครับ)

2017-12-03 17:47 UTC, champillon commented on src/test/java/th/ac/kmitl/science/comsci/example/models/CompanyTest.java
> +        canInitialUniversalCommunication(seller);
ลบออกทั้งบรรทัด 21 และ 22 ครับ ใช้ @Test แทนครับ ตามที่เมนท์ไปด้านล่าง

2017-12-03 17:47 UTC, champillon commented on src/test/java/th/ac/kmitl/science/comsci/example/models/CompanyTest.java
> +   public void cannotChangeUniversalCommunication(Company seller) {
ใส่ @Test เหมือนที่แนะนำไปด้านบนครับ

2017-12-04 00:36 UTC, poyapoyassgit commented on src/main/java/th/ac/kmitl/science/comsci/example/models/Company.java
> +        if(universalcommunication == null) {
ถ้า Company อยาก set E-mail กับ URL ใหม่ ผมอยากให้ใช้คำสั่ง instance.getUniversalCommunivation.setEmail(); อย่างเดียว หรือว่าผมควรยอมให้ Set แบบสร้าง instance ใหม่ด้วยครับ

2017-12-04 00:36 UTC, poyapoyassgit commented on src/main/java/th/ac/kmitl/science/comsci/example/models/Company.java
> +        if(universalcommunication == null) {
ถ้า Company อยาก set E-mail กับ URL ใหม่ ผมอยากให้ใช้คำสั่ง instance.getUniversalCommunivation.setEmail(); อย่างเดียว หรือว่าผมควรยอมให้ Set แบบสร้าง instance ใหม่ด้วยครับ

2017-12-04 01:39 UTC, champillon requested changes
ตอบให้ละครับ

2017-12-04 01:39 UTC, champillon commented on src/main/java/th/ac/kmitl/science/comsci/example/models/Company.java
> +        if(universalcommunication == null) {
พี่ว่าทำได้ 2 ทางครับ
1. ให้ setUniversalCommunication ใหม่ได้ ก็จะไม่ต้องเช็ค if ในนี้
2. ถ้าไม่ให้ set ใหม่ เวลา set ครั้งที่ 2 ควรโยน exception ครับ และเขียน test ดัก exception นั้นด้วย เพราะการที่มันทำงานสำเร็จ กับทำงานไม่สำเร็จ ไม่ควรได้ result เหมือนกันนะครับ

2017-12-04 01:58 UTC, champillon requested changes
แก้อีกนิดเดียวครับ

code เริ่มสวยและไม่ซับซ้อนแล้วครับ ^^b

2017-12-04 01:58 UTC, champillon commented on src/main/java/th/ac/kmitl/science/comsci/example/models/Company.java
> +    private UniversalCommunication universalcommunication;
universalCommunication ครับ (ต้องเป็น camel case ครับ)

2017-12-04 02:01 UTC, champillon commented
อันนี้แนะนำเพิ่มเติมครับ @poyapoyassgit @nukkung999 
ตอนนี้จะเห็นได้ว่า test ของเรามี CompanyTest กับ UniversalCommunicationTest ซึ่งใช้ data test ชุดเดียวกัน
เราสามารถแยก data test มาเป็นอีก component นึงได้ครับ เวลาแก้ไข data test จะได้แก้ไขที่เดียวกัน

อาจจะอยู่ใน package ชื่อ mocks แล้วอาจให้ชื่อว่า CompanyMock เป็น Singleton
เวลาใช้งานก็จะเป็น CompanyMock.name หรือ UniversalCommunicationMock.newEmail อะไรแบบนี้ครับ

เพื่อ control ให้ data test ใช้ชุดเดียวกัน จะได้กันพลาดเวลาพิม และไม่ต้องพิมซ้ำ

2017-12-04 02:02 UTC, champillon approved these changes
Look Good To Me (LGTM) la !!!

2017-12-04 02:20 UTC, khemtat requested changes

2017-12-04 02:20 UTC, khemtat commented on src/main/java/th/ac/kmitl/science/comsci/example/models/UniversalCommunication.java
> +    private String urlID = "";
อันนี้อ้างอิงตามเอกสาร ขมธอ 3-2560 ของ ETDA จะไม่ใช่ url id นะครับ แต่จะเป็น uri id ซึ่งก็คืออีเมลครับ

2017-12-04 04:46 UTC, khemtat requested changes

2017-12-04 04:46 UTC, khemtat commented on src/test/java/th/ac/kmitl/science/comsci/example/models/CompanyTest.java
> +        String uriId = "www.cat202.com";
อ้างอิงตามเอกสารของ ETDA `URI ID` จะเป็นข้อมูลที่เป็นอีเมลนะครับ

2017-12-04 05:02 UTC, poyapoyassgit commented on src/test/java/th/ac/kmitl/science/comsci/example/models/CompanyTest.java
> +        String uriId = "www.cat202.com";
ถ้าอย่างนั้น uriId = "Cat202@hotmail.com" อย่างงี้หรอครับ แล้วต่างจาก Email ยังไงครับ

2017-12-04 05:14 UTC, khemtat commented on src/test/java/th/ac/kmitl/science/comsci/example/models/CompanyTest.java
> +        String uriId = "www.cat202.com";
field email จริง ๆ ไม่มีนะครับในนั้น ตัวอย่างของ xml ที่ ETDA ทำไว้จะใช้เป็น `URI ID` เพื่อเก็บข้อมูล email แทนครับ ลองดูตาม เอกสาร `ขมธอ 3-2560` ครับ

2017-12-04 05:20 UTC, poyapoyassgit commented on src/test/java/th/ac/kmitl/science/comsci/example/models/CompanyTest.java
> +        String uriId = "www.cat202.com";
![1234pmee](https://user-images.githubusercontent.com/33254732/33537255-3fd0962c-d8ed-11e7-9b00-520b7ad4dd0b.PNG)
อันนี้คือของ  ขมธอ. 3-2558  ที่พี่แชมป์โพสต์ในกลุ่ม ถ้าอย่างนั้นผมแก้แค่  uriId เป็น "Cat202@hotmail.com"  แต่ผมไม่ลบ Email นะครับ พี่จะว่าอย่างไรครับ

2017-12-04 05:25 UTC, khemtat commented on src/test/java/th/ac/kmitl/science/comsci/example/models/CompanyTest.java
> +        String uriId = "www.cat202.com";
@champillon

2017-12-04 05:59 UTC, champillon commented on src/test/java/th/ac/kmitl/science/comsci/example/models/CompanyTest.java
> +        String uriId = "www.cat202.com";
@poyapoyassgit อันนี้เป็นไปตาม Spec ของ ETDA ครับ พี่ก็ไม่สามารถอธิบายได้เหมือนกัน พูดง่ายๆว่า ถ้าไม่ทำ ก็ไม่ถูกต้องตามกฏหมายครับ

2017-12-04 06:07 UTC, poyapoyassgit commented on src/test/java/th/ac/kmitl/science/comsci/example/models/CompanyTest.java
> +        String uriId = "www.cat202.com";
![12345pchamp](https://user-images.githubusercontent.com/33254732/33538404-c882fa04-d8f3-11e7-8027-ad60a434172e.PNG)
งั้นผมขออ้างตามเอกสาร ขมธอ 3-2560 ที่ใหม่กว่า ของที่พี่แชมป์โพสต์ในกลุ่มซึ่งเป็น ขมธอ. 3-2558 จะเหลือตัวแปรเพียงหนึ่งตัวใน UniversalCommunication ซึ่งก็คือ uriId

2017-12-04 06:29 UTC, champillon commented on src/test/java/th/ac/kmitl/science/comsci/example/models/CompanyTest.java
> +        String uriId = "www.cat202.com";
@poyapoyassgit งั้นก็ตามนั้นครับ (พี่ดูผิดเอง โทษที) งั้นใช้ฟิลด์ uriId เป็น email แล้วเหลือ field เดียวครับ

2017-12-04 06:44 UTC, khemtat approved these changes

2017-12-04 06:50 UTC, merged

2017-12-04 07:13 UTC, champillon commented
ตัดคะแนนดังนี้

1. design as components (1 คะแนน) => ยังไม่ให้เต็ม 2 คะแนน เพราะยังไม่ได้ใช้ design pattern ที่ยากกว่านี้ ลองหาส่วนอื่นนอกจาก model ทำดูครับ มันมีจุดที่ได้ใช้ design pattern ที่ยากกว่านี้ แล้วจะได้คะแนนเต็ม 2 คะแนนครับ (ถ้าทำได้สมบูรณ์)

2. naming & convention (0.5 คะแนน) => ตัดคะแนนดังนี้
2.1 บางทีชื่อตัวแปรเป็นตัวใหญ่บ้าง และลืมเป็น Camel Case
2.2 การจัด Spacing ของย่อหน้า และบรรทัด ยังไม่เหมาะสม

3. technology leveraging (0 คะแนน) => ยังไม่ได้ใช้ tech อะไรยากครับ ไม่มีคะแนนให้

4. git usage (0.75 คะแนน) => ตัด 0.25 คะแนน เพราะ commit log แรกๆ เขียนไม่สื่อ แต่ commit หลังๆเริ่มดีขึ้น และสื่อว่าไฟล์นี้ถูกแก้ไขอะไรไปบ้างครับ

สู้ๆนะครับ PR ต่อๆไปจะดีขึ้นครับ
@poyapoyassgit